[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
asyncio_mode = "auto"
testpaths = ["tests"]
markers = [
    "security: marks tests as security tests"
]